# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_sessionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='pnumber',
            field=models.CharField(default=11, max_length=11),
            preserve_default=False,
        ),
    ]
